# Generated by Django 5.1.2 on 2024-10-09 15:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('social_name', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=16, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('address_street', models.CharField(blank=True, max_length=255, null=True)),
                ('address_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address_city', models.CharField(blank=True, max_length=255, null=True)),
                ('address_state', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'business',
                'verbose_name_plural': 'businesses',
                'db_table': 'business',
                'ordering': ['id'],
            },
        ),
    ]
